# $Id: Makefile.linux, sept. 16 2002
#------------------------------------------------------
# Make your own and use it or use the one in BASELINE
#------------------------------------------------------

#-----------------------------------------------------------------------------
# Choose a compiler & its options
#--------------------------------------------------------------------------
 CC = g++

 CXX = g++

 #OPTS = -O2 -MMD -D_STL_PORT -DGB 
 OPTS = -O2 -MMD 

 INCLUDE = -I/usr/local/include

 CFLAGS     = $(OPTS) $(INCLUDE) -I.
 CXXFLAGS   = $(CFLAGS) 
 
 TARGET = libmathtool.a 
 default_target: libmathtool.a example


#--------------------------------------------------------------------
.SUFFIXES: .cpp
.cpp.o:
	$(CC) ${CFLAGS} -c $<
	cat $*.d >> Dependencies
	rm -f $*.d

#--------------------------------------------------------------------
OBJS         =  Basic.o EulerAngle.o  Gauss.o  Matrix.o  Quaternion.o

objs: ${OBJS}
#--------------------------------------------------------------------
$(TARGET): objs
	ar cru $(TARGET) $(OBJS)
#	libtool -static -o $(TARGET) $(OBJS)

example:
	$(CC) ${CXXFLAGS} -L. -lmathtool example.cpp -o example
	cat example.d >> Dependencies
	rm -f example.d

clean:
	rm -f *.o $(TARGET) example Dependencies
	touch Dependencies

include Dependencies
